AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'This template defines the resources for the API Gateway infrastructure.

  '
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prod
    Description: The environment to deploy the resources to
  ProjectName:
    Type: String
    Description: The name of the project
    Default: km-test
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.us-west-2.amazonaws.com/s3-km-test/170a259257da42ac25a624c9cb102e30.template
      Parameters:
        Environment:
          Ref: Environment
        ProjectName:
          Ref: ProjectName
    Metadata:
      SamResourceId: LambdaFunction
  API:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.us-west-2.amazonaws.com/s3-km-test/3eb7f31f88b4aa7c69808faa95dcf5e4.template
      Parameters:
        Environment:
          Ref: Environment
        ProjectName:
          Ref: ProjectName
        POSTHandlerFunctionArn:
          Fn::GetAtt:
          - LambdaFunction
          - Outputs.POSTHandlerFunctionArn
        GETHandlerFunctionArn:
          Fn::GetAtt:
          - LambdaFunction
          - Outputs.GETHandlerFunctionArn
    Metadata:
      SamResourceId: API
Outputs:
  API:
    Description: The API Gateway endpoint.
    Value:
      Fn::GetAtt:
      - API
      - Outputs.EndpointURL
