# api.yaml

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
  POSTHandlerFunctionArn:
    Type: String
  GETHandlerFunctionArn:
    Type: String
  UserPoolArn:
    Type: String
    
Resources:
  # CognitoAuthorizer:
  #   Type: AWS::ApiGateway::Authorizer
  #   Properties:
  #     Name: CognitoAuthorizer
  #     Type: COGNITO_USER_POOLS
  #     RestApiId: !Ref ApiID
  #     IdentitySource: method.request.header.Authorization
  #     ProviderARNs:
  #       - !Ref UserPoolArn

  API:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      EndpointConfiguration:
          Type: REGIONAL
      # Auth:
      #   DefaultAuthorizer: CognitoAuthorizer
      #   Authorizers:
      #     CognitoAuthorizer:
      #       UserPoolArn: !Ref UserPoolArn
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ../resources/api/openapi-generated.yaml

Outputs:
  EndpointURL:
    Description: The API Gateway endpoint.
    Value: !Sub "https://${API}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"